on: push
jobs:
  test-pyreindexer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test PyReindexer
        env:
          PYRX_GH_TOKEN: ${{ secrets.PYRX_GH_TOKEN }}
        run: .github/workflows/pyreindexer_workflow.sh
        shell: bash

